name: unci-maka-py
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - shapely
  - folium
  - rioxarray
  - rasterio
  - gdal
  - pyproj
  - cartopy
  - xarray
  - netCDF4
  - h5netcdf
  - dask
  - zarr
  - holoviews
  - hvplot
  - earthaccess
  - spectral
  - scikit-image
  - pip
  - pip:
      - localtileserver